Add arm swing packet translator
DragonetMC/DragonProxy pull request #174
Opened 2017-12-29 22:56 UTC by johnnywoof

This will make it so that java clients will see arm swings from PE clients.

2017-12-30 09:12 UTC, DefinitlyEvil requested changes

2017-12-30 09:12 UTC, DefinitlyEvil commented on src/main/java/org/dragonet/proxy/network/PacketTranslatorRegister.java
> +		PE_TO_PC_TRANSLATOR.put(AnimatePacket.class, new PEAnimatePacketTranslator());
Extra spaces xD

2017-12-30 09:12 UTC, DefinitlyEvil commented on src/main/java/org/dragonet/proxy/network/translator/pe/PEAnimatePacketTranslator.java
> +				return new Packet[]{};
You can just return null. ;)

2017-12-31 01:57 UTC, DefinitlyEvil approved these changes

2017-12-31 11:51 UTC, HoverEpic requested changes
Same here, \t formating is not good, use 4 spaces.

2017-12-31 17:16 UTC, johnnywoof commented
My bad, sorry about that. It should use spaces now

2017-12-31 17:44 UTC, HoverEpic approved these changes

2017-12-31 17:44 UTC, merged