Beds, Heads and banners
DragonetMC/DragonProxy pull request #551
Opened 2020-05-03 00:09 UTC by james090500

Fixes rotation/type of heads #519 
Fixes banner types #522 
Fixes bed types #507

2020-05-03 00:48 UTC, lukeeey requested changes

2020-05-03 00:48 UTC, lukeeey commented on proxy/src/main/java/org/dragonet/proxy/network/session/cache/ChunkCache.java
> +                int x = Integer.parseInt(column.getTileEntities()[i].get("x").getValue().toString());
You can also cast it to an IntTag rather than returning it as a string and parsing it

2020-05-03 00:48 UTC, lukeeey commented on proxy/src/main/java/org/dragonet/proxy/network/translator/misc/item/BannerItemTranslator.java
> +            return null;
This is an issue because it will add null to the patternList. Add a null check above.

2020-05-03 10:32 UTC, lukeeey requested changes

2020-05-03 10:32 UTC, lukeeey commented on proxy/src/main/java/org/dragonet/proxy/network/translator/java/world/PCBlockValueTranslator.java
> +        if(packet.getBlockId() == PISTON || packet.getBlockId() == STICKY_PISTON) {
if packet.getType() instanceof PistonValueType

2020-05-03 16:31 UTC, james090500 commented
This also fixes piston heads but they only show when piston is updated #538

2020-05-04 11:25 UTC, lukeeey approved these changes

2020-05-04 11:25 UTC, merged